env=staging
browser=chrome
headless=false
remote=false
remote.url=http://localhost:4444/wd/hub
base.url=https://www.saucedemo.com
timeout.seconds=15
download.dir=target/downloads
window.size=1920,1080
browserstack.enabled=false
browserstack.username=
browserstack.accessKey=
